### ISSUE TITLE
Does not work after multiple tries

### ISSUE THREAD

**Issue by samfishersam** [jkjoschua/poe-ladder-tracker-java#2]
Hi,

I'm having issues getting this to work.  I've been trying over 9 hours closing and waiting for the appropriate amount of time as you mentioned and it just counts till 500+ and says PoE website is down. v1.1, Legacy

**Comment by jkjoschua** [comment]
Hey,

in worst case the tool will not woto wait 1 hour because you received a timeout from the CSV export page (this can only happen if the tool was restarted too fast). To avoid that stop the tool, wait 5 minutes and start again.

But this seems not to be the problem at your side. It sounds more likely java is not allowed to download or something like that. Any security tools running? Which java is installed?

**Comment by samfishersam** [comment]
Yup, I waited 1 hour for 9 times :P Java is allowed to run, cos I am using Mercury Trade as well which uses Java. Java 8 Update 121

**Comment by jkjoschua** [comment]
Okay, please run it from the console like "java -jar Ladder-Tracker-v1.1.jar". 
There can be alot of warnings at the startup which can be ignored. If the tool was not able to download CSVs there will be a line like "Error downloading CSV1!". Post the error code behind.

**Comment by samfishersam** [comment]
I'm getting this error when running from CMD

http://i.imgur.com/X3PQHQf.png

**Comment by jkjoschua** [comment]
Not an error and normal, wait for Error downloading CSV1!

**Comment by samfishersam** [comment]
I just got that error now.  A whole string of errors all the way up to CSV7.
http://imgur.com/a/gHwjj

**Comment by jkjoschua** [comment]
Okay can you please whisper me ingame. IGN Joschn

**Comment by jkjoschua** [comment]
So this is the error for a CSV export timeout.

We talked ingame about that: he should exit the tool and try it again after 1 hour. Since then no feedback, so I guess his problem is solved.
